---
title: "Response to Burns et al"
author: "Travis Gerke, Konrad Stopsack"
date: '`r strftime(Sys.time(), "%A, %b %d, %Y")`'
mainfont: 'Source Serif Pro'
monofont: 'Source Code Pro'
output:
  github_document: default
  rmarkdown::html_vignette:
    df_print: kable
    standalone: true
  pdf_document: 
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE,
  warning = FALSE, message = FALSE,
  fig.width = 10, fig.height = 7, 
  fig.showtext = TRUE # for the fancy fonts, disable if not needed
)
```

```{css global-css, echo=FALSE}
img {
  margin: 0;
  padding: 0;
  max-width: 100%;
}
```

```{r library, include=FALSE}
library(tidyverse)
library(popEpi)  # for use of sir()
library(kableExtra)

# Use the grkmisc theme
# theme_set(
#   grkmisc::theme_grk(
#     base_family = "Source Serif Pro",
#     axis_text_family = "Source Code Pro",
#     axis_title_family = "Source Serif Pro",
#     default_geom_font = "Source Sans Pro",
#     use_showtext = TRUE
#   ) + 
#     theme(panel.grid.minor = element_blank())
# )
```
   
```{r load, include=FALSE}
# Load Data

# CDC United States Cancer Statistics 1999-2015 from 
# https://www.cdc.gov/cancer/uscs/USCS_1999_2015_ASCII.zip via
# https://www.cdc.gov/cancer/uscs/dataviz/download_data.htm
uscs <- read_delim(file = "data/BYAGE.TXT", delim = "|", guess_max = 250000)

# Use 2014 incidence rates (end of inclusion in Burns et al.)
uscs <- uscs %>% 
  rename_all(tolower) %>%
  filter(site == "Prostate" & sex == "Male" & year == "2014" &
                   event_type == "Incidence" & race == "All Races" & rate != "~")
# recast as a reference table by decade of life
ref <- uscs %>% 
  filter(!(age %in% c("80-84", "85+"))) %>%
  mutate(decade = as.numeric(str_sub(age, 1, 1))*10, 
         count = as.numeric(count)) %>%
  group_by(decade) %>% #one assumption is that 35-40 represents the full 30 decade
  summarise(count = sum(count), 
            population = sum(population)) %>%
  mutate(rate = count/population*100000)

# Input Burns et al., Eur Urol 2018, Table 1 counts
burns <- tibble(decade = rep(c(30, 40, 50, 60, 70), 2), # Start of age category
                n      = c(630, 2602, 3304, 1978, 792, 70, 288, 366, 221, 47), # Person counts 
                cases  = c(29, rep(NA, 4), 30, rep(NA, 4)), # 5-yr cumulative incidence of total PCa
                group  = as.factor(c(rep("Non-IBD", 5), rep("IBD", 5))), 
                followUp = n*5 #assumption of 5 years on average per patient 
                )
```

## Data analysis

Age-specific prostate cancer incidence rates per 100,000 person-years for 2014 from CDC United States Cancer Statistics (https://www.cdc.gov/cancer/uscs/USCS_1999_2015_ASCII.zip via
https://www.cdc.gov/cancer/uscs/dataviz/download_data.htm)

```{r} 
uscs %>% 
  select(-event_type, -sex, -year) %>%
  kable()
```

Data as presented in Table 1 of Burns et al.

```{r} 
burns %>% 
  select(-followUp) %>%
  kable()
```

## Results 

```{r}
dat <- left_join(ref, burns, by = "decade") %>% 
  mutate(expected = followUp*rate/100000) %>%
        group_by(group)

# do expected by hand
dat %>% summarise(E = sum(expected))
  
sir(coh.data = dat %>% mutate(py = n*5), 
    coh.pyrs = py,
    coh.obs = cases, 
    ref.data = dat,
    ref.obs = count,
    ref.pyrs = population,
    adjust = decade,
    print = group)
```

<!-- Start Document Here -->